config/routes.rb
SafeFare::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users do
    resources :restaurants do
     resources :type_of_cuisines
      resources :aware_employees do
        resources :restaurant_roles
      end
    end
  end
resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

 match "/restaurants/:url" => "restaurants#show", via: [:get]

  root 'home#index'
  match "/about" => "home#about", via: [:get, :post]
  match "/about/contact-us" => "home#contact", via: [:get]
  match "/about/privacy-policy" => "home#privacy_policy", via: [:get]
  match "/submit" => "home#submit", via: [:post]
  match "/find-a-restaurant" => "search#index", via: [:get]
  match "/results" => "search#results", via: [:post, :get]
  match "/for-diners" => "home#for_diners", via: [:get]
  match "/for-restaurants" => "home#for_restaurants", via: [:get, :post]
  match "/sitemap" => "home#sitemap", via: [:get, :post]
  match "/disclaimer" => "home#disclaimer", via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :restaurants,
  dependent: :destroy,
  inverse_of: :user

  has_many :changeorders,
  	inverse_of: :user
  	
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable, :confirmable


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index 
  end
  
  def show
    @user = User.find(params[:id])
    @restaurants = @user.restaurants
  end

def update_password
    @user = User.find(current_user.id)
    if @user.update(user_params)
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to @user, notice: "Successfully Updated "
    else
      redirect_to @user, notice: @user.errors.full_messages 
    end
  end

  def new
  end
   private

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.required(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if current_user == @user %>
<div class="user-section">
  <div class="alert notice"><%= notice %><%= alert %></div> 
  <div class="section-wrapper">
    <div class="col-sm-12">
      <h1>Welcome <%=@user.name%></h1>
      <!-- <a href="" class="nav-link right orange">DELETE MY ACCOUNT</a> -->
      <%= link_to "DELETE MY ACCOUNT", user_registration_path(resource_name),:class=>'nav-link right orange', :confirm => "Are you sure?", :method => :delete %>
      <div class="tb-wrap">
      <%= link_to "ADD RESTAURANT" , new_user_restaurant_path(current_user), class: "right nav-link add-rest" %><h2>My Restaurants</h2>
            <table class="tablesorter">
              <thead>
                <tr class='order'>
                  <th class="center edit">Edit</th>
                  <th>Restaurant Name</th>
                  <th class="center"># Employees</th>
                  <th class="center">% Trained</th>
                  <th class="center">Approved</th>
                </tr>
              </thead>

              <tbody>
                <% @restaurants.each do |restaurant| %>
                  <tr>
                    <td class="center edit"><a href="/users/<%=@user.id%>/restaurants/<%=restaurant.id%>/edit" class="edit-button"></a></td>
                    <td class='title'><a href='/users/<%=@user.id%>/restaurants/<%=restaurant.id%>/edit'><%= restaurant.name %></a><br><a href="/restaurants/<%= restaurant.url %>"><%= restaurant.address %></td>
                    <td class="center"><%= restaurant.total_employees %></td>
                    <td class="center"><% percent = (restaurant.aware_employees.length.to_f / restaurant.total_employees.to_f ) * 100 %>
                    <%= percent.round %>
                    </td>
                    <% if restaurant.approved %>
                    <td class="center"><div class="approved"></div></td>
                    <%else%>
                     <td class="center"><div class="approved not" style='text-align:center;'>Pending</div></td>
                    <%end%>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="rest-tbl-message"><span class="required_field">*</span>To edit your restaurant information, please click on the name of your restaurant, above.  If you wish to change your password, please fill in the fields below.</div>
      <div class="blue-form accounts">
          <div class="col-sm-12" >
            <h2>Account Information</h2>
            <hr>
            <%= form_for(@user, :url => { :action => "update_password" } ) do |f| %>
              <%= devise_error_messages! %>
              <div class="col-xs-12 form-row validate name">
              <p class='form-label'>Email</p>
                <h2 class='input'><%=@user.email%></h2>
              </div>
              <div class="col-xs-12 form-row validate name">
              <p class='form-label'>New Password</p>
                <%= f.password_field :password, :autocomplete => "off"  %>
              </div>
               <div class="col-xs-12 form-row validate name">
              <p class='form-label'>Re-Type Password</p>
              <%= f.password_field :password_confirmation %>
              <div class='feedback'><div></div></div>
            </div>
              <div class="action_container" style='margin:auto;'>
                <%= f.submit%>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>
<%else%>
  <div class="col-sm-12" style='text-align:center;'>
      <div class="center error">
        <h1>You've ended up in the wrong place</h1>
        <%= link_to "Get Me Out Of Here!", '/for-restaurants', class:'nav-link' %>
      </div>  
  </div>
<%end%>