config/routes.rb
SafeFare::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users do
    resources :restaurants do
     resources :type_of_cuisines
      resources :aware_employees do
        resources :restaurant_roles
      end
    end
  end
resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

 match "/restaurants/:url" => "restaurants#show", via: [:get]

  root 'home#index'
  match "/about" => "home#about", via: [:get, :post]
  match "/about/contact-us" => "home#contact", via: [:get]
  match "/about/privacy-policy" => "home#privacy_policy", via: [:get]
  match "/submit" => "home#submit", via: [:post]
  match "/find-a-restaurant" => "search#index", via: [:get]
  match "/results" => "search#results", via: [:post, :get]
  match "/for-diners" => "home#for_diners", via: [:get]
  match "/for-restaurants" => "home#for_restaurants", via: [:get, :post]
  match "/sitemap" => "home#sitemap", via: [:get, :post]
  match "/disclaimer" => "home#disclaimer", via: [:get, :post]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_fare
	def index
	end
	def about
	end
	def sitemap
	end
	def contact
		@contactform = ContactForm.new
	end
	def about
	end
	def disclaimer
	end
	def submit
		
		@form = ContactForm.new(form_params)
	      if @form.valid?
		    @form.deliver!  
	        redirect_to :back, notice: "<h1 style='text-align:center'>A Message from FARE</h1>Thank you for getting in touch with us.  We will review your message and will respond shortly regarding your comments/inquiry.<br>
	        Sincerely,<br>
	        Food Allergy Research & Education (FARE)<br>
	        <br>
	        <span style='font-style:italic;''>FARE’s mission is to find a cure for food allergies and to keep individuals with food allergies safe and included. Learn more at  #{ActionController::Base.helpers.link_to "www.foodallergy.org", 'http://www.foodallergy.org'} </span>".html_safe
	      else
	        redirect_to :back, notice: 'Sorry, there was an error processing your form.  Please try again'
	      end
	end
    def for_diners
    end
    def for_restaurants
    end
	private
    def form_params
      params.require(:contact_form).permit(:message, :name,:email,:subject, :restaurant_owner, :employee, :member, :zip, :other, :parent)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="about-section">
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="" class='active'>About SafeFARE</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1 class="orange-header">About SafeFARE</h1>
			<p>Enjoying restaurant meals with friends and family doesn&#8217;t have to be off limits just because you have a food allergy. With the right planning and preparation, eating out can still be an enjoyable part of your life. That&#8217;s why <a href="http://foodallergy.org" rel="external" title="http://foodallergy.org">Food Allergy Research & Education (FARE)</a> &#8211; the nation&#8217;s leading organization working on behalf of the 15 million Americans with food allergy &#8211; has created the SafeFARE program.</a></p>
			<p>If you or someone you love has a food allergy &#8211; or if you&#8217;re a restaurant or foodservice professional committed to accommodating diners with food allergies &#8211; SafeFARE offers tools and resources that help create a safer dining experience:</p>
			<hr>
			<div class="row">
				<div class="col-sm-3">
					<a href="/find-a-restaurant"><div class="find-a-button"></div></a>
				</div>
				<div class="col-sm-9 col-xs-12">
					<h2><a href="/find-a-restaurant">Find a Restaurant</a></h2>
					<p>Use our searchable database to find food allergy aware restaurants near you. Staff at these restaurants have completed the industry&#8217;s most trusted food allergy training programs: the National Restaurant Association&#8217;s <a href="http://www.servsafe.com/allergens" rel="external" title="http://www.servsafe.com/allergens">ServSafe&reg; Allergens Online Course</a> or <a href="http://www.menutrinfo.com/allergy-training/" rel="external" title="http://www.menutrinfo.com/allergy-training/">MenuTrinfo&#8217;s AllerTrain&trade;</a> course.</p>
					<p><strong>Restaurants:  Do you have staff members who have completed these courses? <a href="/for-restaurants">Add your restaurant to our database!</a></strong></p>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-3">
					<a href="/for-diners"><div class="resources-button"></div></a>
				</div>
				<div class="col-sm-9 col-xs-12">
					<h2><a href="/for-diners">Food Allergy Resources</a></h2>
					<p>Explore our resource library for expert advice and information about dining out with food allergies&#8211;including a chef card that you can download and personalize.</p>
				</div>
			</div>
		</div>
		<div class="col-sm-4 col-xs-12 right-section">
			<a class='contact-link' href="/about/contact-us">
				Contact Us
			</a>
			<%= image_tag("thumb-placeholder.png",class:"PSA", :alt => "temp thumbnail") %>
			<p style='width: 85%; margin: auto;'class='padding-top'>Watch our “Food Allergy Teamwork” PSA featuring celebrity chefs Mike Isabella and Bryan Voltaggio!</p>
		</div>
	</div>
</div>
<div style='clear:both'></div>

app/views/home/contact.html.erb
<div class="contact-section">
	<div class="alert notice"><%= notice %><%= alert %></div> 
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="/about">About > </a></li>
			  <li><a href="/about/contact-us" class='active'> Contact Us</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>Contact Us</h1>
			<p><a href="http://www.foodallergy.org" rel="external" title="http://www.foodallergy.org">Food Allergy Research &amp; Education (FARE)</a> is the nation’s leading national organization working on behalf of the 15 million Americans with food allergy. Our mission is to find a cure for food allergies, and to keep individuals with food allergies safe and included. We do this by investing in world-class research that advances treatment and understanding of the disease; providing evidence-based education and resources; undertaking advocacy at all levels of government; and increasing awareness of food allergy as a serious and growing public health issue.</p>
			<p>To learn more about food allergy, FARE or the SafeFARE program, please fill in the fields below.</p>
			<div class="contact-form">
				<%= simple_form_for @contactform, url: "/submit", method: :post do |f| %>
					<div class="col-sm-12 form-row">
						<p class='form-label'>Full Name</p>
						<%= f.input :name, label: false%>
					</div>
					<div class="col-sm-12 form-row">
						<p class='form-label'>I am</p>
						<div class="i-am-cat right">
						<%= f.input :parent, label: "a parent" ,as: :boolean%>
						<%= f.input :member, label: "a person managing food allergies" ,as: :boolean%>
						<%= f.input :restaurant_owner, label: "a restaurant owner" ,as: :boolean%>
						<%= f.input :employee, label: "a restaurant employee" ,as: :boolean%>
						<%= f.input :other, label: "other" ,as: :boolean%>
						</div>
					</div> 
					<div class="col-sm-12 form-row">
						<p class='form-label'>Email</p>
						<%= f.input :email, label: false  %>
					</div>
					<div class="col-sm-12 form-row">
						<p class='form-label'>ZIP</p>
						<%= f.input :zip, label: false  %>
					</div>

					<div class="col-sm-12 form-row">
						<p class='form-label'>Subject</p>
						<%= f.input :subject, label: false  %>
					</div>
		
					<div class="col-sm-12 form-row">
						<p class='form-label'>Message</p>
						<%= f.input :message, label: false, :as => :text  %>
					</div>
					<div class="col-sm-12 form-row">
						<div class="no-label-wrap">
							<%= f.submit "SUBMIT" %>
						</div>
					</div>
				<%end%>
			</div>
		</div>
		<div class="col-sm-4 col-xs-12 right ">
			<h1>National Office</h1>
			<address>
				<div class="vcard">
					<div class="street-address">7925 Jones Branch Drive</div>
					<div>Suite 1100</div>
					<div>
						<span class="locality">McLean</span>, 
						<span class="region">VA</span>, 
						<span class="postal-code">22102</span>
						<span class="country-name">USA</span>
					</div>
					<div class="tel">Toll-Free: 800-929-4040</div>
					<div class="tel">Main: 703-691-3179</div>
					<div class="fax">Fax: 703-691-2713</div>
				</div>		
			</address>
		</div>
	</div>
	<div style='clear:both'></div>
</div>

app/views/home/diners.html.erb
<div class="diners-section">
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="/for-diners" class='active'>For Diners</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>For Diners</h1>

			<p>Whether your plans call for dinner at a hot new restaurant or lunch at the neighborhood diner, being prepared is the key to eating out safely with food allergies. Calling in advance, bringing a chef card (like the one below) and choosing a food allergy aware restaurant are a few of the things you can do to make your experience safe and enjoyable. And of course, bringing along your emergency medications will give you peace of mind.</p>
			<hr>
			<h2>Tools</h2>
			<p>Food Allergy Research & Education (FARE) created the SafeFARE program to give you the tools you need to enjoy eating out with family and friends. Follow the links below to find important information about managing food allergies while dining out. Bon apétit!</p>
			<ul>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go">Before You Go</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant">Calling the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant">At the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide">&#8220;Insider&#8217;s Guide to Dining Out&#8221; by Chef Joel Schaefer</a></li>
				<li><a href="#" rel="external" title="#">Find Allergy Aware Restaurants</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees">Allergen Training for Restaurant Staff</a></li>
			</ul>
				<div><a href="http://www.foodallergy.org/document.doc?id=230" rel="external" title="http://www.foodallergy.org/document.doc?id=230">Download a PDF of all dining out resources</a></div>
				<div><a href="http://www.foodallergy.org/document.doc?id=219" rel="external" title="http://www.foodallergy.org/document.doc?id=219">Download a chef card</a></div>
			<hr>
			<h2>Helpful Resources</h2>
			<p>Print or email these flyers to let restaurants in your area know about food allergy training programs:</p>
			<ul>
				<li><a href="http://www.foodallergy.org/document.doc?id=226" rel="external" title="http://www.foodallergy.org/document.doc?id=226">ServSafe&reg; Allergens Online Course (National Restaurant Association)</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=262" rel="external" title="http://www.foodallergy.org/document.doc?id=262">AllerTrain&trade; Classes (MenuTrinfo)</a></li>
			</ul>
			<hr>
			<h2>Ingredient Quiz – Test Your Knowledge!</h2>
			<p>Think you know all there is to know about meal ingredients that might turn up in a restaurant? Download the following quiz, put together by Chef Joel Schaefer, to see how much you really know.</p>
			<ul>
				<li><a href="http://www.foodallergy.org/document.doc?id=222" rel="external" title="http://www.foodallergy.org/document.doc?id=222">Quiz</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=221" rel="external" title="http://www.foodallergy.org/document.doc?id=221">Answer key. No cheating!</a></li>
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12 right-section">
			<%= image_tag("thumb-placeholder.png",class:"PSA", :alt => "temp thumbnail") %>
			<p style='width: 85%; margin: auto;'class='padding-top'>Watch our “Food Allergy Teamwork” PSA featuring celebrity chefs Mike Isabella and Spike Mendelsohn!</p>
		</div>
	</div>
</div>
<div style='clear:both'></div>

app/views/home/disclaimer.html.erb
<div class="sitemap-section">
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="/disclaimer" class='active'>Disclaimer</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>Disclaimer</h1>
			<p>Thank you for visiting Food Allergy Research &amp; Education’s (FARE) SafeFARE site.</p>
 
			<p>The information provided on this site is designed to support, not replace, the relationship that exists between a patient/site visitor and his/her existing physician.</p>
			 
			<p>The material on this website was written to provide a guideline for care. The authors and FARE disclaim any responsibility for any adverse effects resulting from the information presented on this website. The information enclosed is not designed to take the place of a doctor's instructions. Patients are urged to contact a doctor for specific information regarding guidelines for care. The inclusion of brand name medications or medical devices does not imply endorsement by FARE.</p>
			 
			<p>FARE does not host any form of advertisement.</p>
		</div>
	</div>
</div>

app/views/home/for_diners.html.erb
<div class="diners-section">
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="/for-diners" class='active'>For Diners</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>For Diners</h1>

			<p>Whether your plans call for dinner at a hot new restaurant or lunch at the neighborhood diner, being prepared is the key to eating out safely with food allergies. Calling in advance, bringing a chef card (like the one below) and choosing a food allergy aware restaurant are a few of the things you can do to make your experience safe and enjoyable. And of course, bringing along your emergency medications will give you peace of mind.</p>
			<hr>
			<h2>Tools</h2>
			<p>Food Allergy Research &amp; Education (FARE) created the SafeFARE program to give you the tools you need to enjoy eating out with family and friends. Follow the links below to find important information about managing food allergies while dining out. Bon apétit!</p>
			<ul>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go">Before You Go</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant">Calling the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant">At the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide">&#8220;Insider&#8217;s Guide to Dining Out&#8221; by Chef Joel Schaefer</a></li>
				<li><a href="/for-restaurants" rel="external" title="#">Find Allergy Aware Restaurants</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees" rel="external" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees">Allergen Training for Restaurant Staff</a></li>
			</ul>
				<div><a href="http://www.foodallergy.org/document.doc?id=230" rel="external" title="http://www.foodallergy.org/document.doc?id=230">Download a PDF of all dining out resources</a></div>
				<div><a href="http://www.foodallergy.org/document.doc?id=219" rel="external" title="http://www.foodallergy.org/document.doc?id=219">Download a chef card</a></div>
			<hr>
			<h2>Helpful Resources</h2>
			<p>Print or email these flyers to let restaurants in your area know about food allergy training programs:</p>
			<ul>
				<li><a href="http://www.foodallergy.org/document.doc?id=226" rel="external" title="http://www.foodallergy.org/document.doc?id=226">ServSafe&reg; Allergens Online Course (National Restaurant Association)</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=262" rel="external" title="http://www.foodallergy.org/document.doc?id=262">AllerTrain&trade; Classes (MenuTrinfo)</a></li>
			</ul>
			<hr>
			<h2>Ingredient Quiz – Test Your Knowledge!</h2>
			<p>Think you know all there is to know about meal ingredients that might turn up in a restaurant? Download the following quiz, put together by Chef Joel Schaefer, to see how much you really know.</p>
			<ul>
				<li><a href="http://www.foodallergy.org/document.doc?id=222" rel="external" title="http://www.foodallergy.org/document.doc?id=222">Quiz</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=221" rel="external" title="http://www.foodallergy.org/document.doc?id=221">Answer key. No cheating!</a></li>
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12 right-section">
			<%= image_tag("thumb-placeholder.png",class:"PSA", :alt => "temp thumbnail") %>
			<p style='width: 85%; margin: auto;'class='padding-top'>Watch our “Food Allergy Teamwork” PSA featuring celebrity chefs Mike Isabella and Spike Mendelsohn!</p>
		</div>
	</div>
</div>
<div style='clear:both'></div>

app/views/home/for_restaurants.html.erb
<div class="about-section">
	<div class="alert notice"><%= notice %><%= alert %></div> 
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="" class='active'>For Restaurants</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>For Restaurants</h1>
			<p>Fifteen million Americans have food allergies – and they are eager to find restaurants that can accommodate them. The SafeFARE program offers tools that help create a safer dining experience – including &#8220;Find a Restaurant,&#8221; a searchable database of allergy aware restaurants. If your employees  have completed the ServSafe® Allergens Online Course or AllerTrain™ classes, be sure to sign up below to set up a free account and add your restaurant to our database. You can sign in to update your account whenever you like.</p>
			<p>If you haven't yet received allergen training, we encourage you to do so! To learn more, please see &#8220;<a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees" rel="external">Allergen Training for Restaurant Staff</a>&#8221;</p>
			<% if !user_signed_in? %>
				<h2>Restaurant Login</h2>
				<div class="contact-form">
					<%= form_for(:user, :url => session_path(:user)) do |f| %>
						<%= devise_error_messages! %>
						<div class="form-row col-sm-12">
							<p class='form-label'>Email</p>
							<%= f.text_field :email, label: false %>
						</div>
						<div class="form-row col-sm-12">
							<p class='form-label'>Password</p>
							<%= f.password_field :password, label: false %>
						</div>
						<div class="form-row col-sm-12">
							<div class="no-label-wrap">
								<%= f.check_box :remember_me %>
								<%= f.label :remember_me %>
							</div>
						</div>
						<div class="form-row col-sm-12">
							<div class="no-label-wrap">
								<%= f.submit 'LOG IN', class: 'login' %>
								
							</div>
						</div>
						<div class="form-row col-sm-12">
							<div class="no-label-wrap">
								<%= link_to "Forgot your password?", new_password_path(:user), class: "forgot-your-password" %>
							</div>
							<div class="no-label-wrap">
								<a class='forgot-your-password' href="/users/sign_up">Sign Up</a>
							</div>
						</div>
					<% end %>
				</div>
			<% else %>
				<hr>
			<% end %>
			<h2>Ingredient Quiz – Test Your Knowledge!</h2>
			<p>Think you know all there is to know about meal ingredients that might turn up in a restaurant? Download the following quiz, put together by Chef Joel Schaefer, to see how much you really know.</p>
			<ul>
				<li><a href="http://www.foodallergy.org/document.doc?id=222" rel="external" title="http://www.foodallergy.org/document.doc?id=222">Quiz</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=221" rel="external" title="http://www.foodallergy.org/document.doc?id=221">Answer key. No cheating!</a></li>
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12">
			<h1 style='text-align:center;'>Resource Library</h1>
			<ul class="link-list">
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/training-for-restaurant-employees" rel="external">Allergen Training for Restaurant Staff</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/before-you-go" rel="external">Before You Go</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/calling-the-restaurant" rel="external">Calling the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/at-the-restaurant" rel="external">At the Restaurant</a></li>
				<li><a href="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide" title="http://www.foodallergy.org/managing-food-allergies-at/dining-out/insiders-guide" rel="external">&#8220;Insider&#8217;s Guide to Dining Out&#8221; by Chef Joel Schaefer</a></li>
				<li><a href="http://www.foodallergy.org/document.doc?id=219" title="http://www.foodallergy.org/document.doc?id=219" rel="external">Sample chef card</a></li>
			</ul>
			<div class="nav-link signup orange" style='margin:auto;'><a href="/users/sign_up">SIGN UP</a></div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="home">
	<div class="alert notice" style='display:none; opacity:0px;'><%= notice %><%= alert %></div> 
	<div class="info-section">
		<div class="section-wrapper">
			<div class="home-background"></div>
			<div class="info-box col-sm-12 no-padding">
				<div class="col-sm-4 col-xs-12 about left no-padding">
					<div class="cont">
						<h1 class='orange-header'>About SafeFARE</h1>
						<p>If you are managing food allergies or are a restaurant professional, SafeFARE provides tools and resources to help you create a safer, more enjoyable dining experience. This program is brought to you by Food Allergy Research &amp; Education (FARE) – the nation’s leading organization working on behalf of the 15 million Americans with food allergy.</p>
					</div>	
				</div>
				<div class="col-sm-4 col-xs-12 vid left no-padding" >
					<%= image_tag("thumb-placeholder.png", :alt => "temp thumbnail") %>
				</div>
				<div class="col-sm-4 for-restaurant left no-padding">
					<div class="cont">
						<h1 class='orange-header'>For Restaurants</h1>
						<p>Have you completed the <a href='http://www.servsafe.com/allergens'>ServSafe® Allergens Online Course</a> or <a href='http://www.menutrinfo.com/allergy-training/'>AllerTrain™?</a> Add your restaurant to our searchable database by setting up a free account.</p>
						<% if user_signed_in? %>
							<div class="nav-link">
					 		   <%= link_to('My Account', current_user) %>
					 		</div>
					 	<% else %>	
						<div class="nav-link">
							<%= link_to "Sign Up Here", "/for-restaurants" %> 
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	
})

</script>

app/views/home/sitemap.html.erb
<div class="sitemap-section">
	<div class="section-wrapper">
		<ul class="safe-fare-breadcrumb">
			  <li><a href="/">Home > </a></li>
			  <li><a href="/sitemap" class='active'>Sitemap</a></li>
		</ul>
		<div class="col-sm-8 col-xs-12">
			<h1>Sitemap</h1>
			<ul>
				<li>
					<a href="/">Home</a>
				</li>
				<li><a href="/about">About SafeFARE</a></li>
				<li><a href="/find-a-restaurant">Find a Restaurant</a></li>
				<li><a href="/for-diners">For Diners</a></li>
				<li><a href="/for-restaurants">For Restaurants</a></li>
				<li><a href="/users/sign_up">Sign Up</a></li>
			</ul>
		</div>
	</div>
</div>