config/routes.rb
SafeFare::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users do
    resources :restaurants do
     resources :type_of_cuisines
      resources :aware_employees do
        resources :restaurant_roles
      end
    end
  end
resource :user, only: [:edit] do
  collection do
    patch 'update_password'
  end
end

 match "/restaurants/:url" => "restaurants#show", via: [:get]

  root 'home#index'
  match "/about" => "home#about", via: [:get, :post]
  match "/about/contact-us" => "home#contact", via: [:get]
  match "/about/privacy-policy" => "home#privacy_policy", via: [:get]
  match "/submit" => "home#submit", via: [:post]
  match "/find-a-restaurant" => "search#index", via: [:get]
  match "/results" => "search#results", via: [:post, :get]
  match "/for-diners" => "home#for_diners", via: [:get]
  match "/for-restaurants" => "home#for_restaurants", via: [:get, :post]
  match "/sitemap" => "home#sitemap", via: [:get, :post]
  match "/disclaimer" => "home#disclaimer", via: [:get, :post]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :logo, ImageUploader

  mount_uploader :image, PictureUploader
  # VALID_STATES = ['CA']

  #  	# State.all.each do |state| 
  #  	# 	VALID_STATES << state.abbreviation
  #  	# end
  scope :pending, where(approved:false)
	validates_presence_of :name, :address, :city, :zip
  
  validates_length_of :phone, :minimum => 10,:allow_nil => true, :allow_blank => true, :message => "Your phone number should be at least ten digits."

  validates_format_of :website, with: URI::regexp(%w(http https)), :allow_blank => true, :allow_nil => true
  # validates_inclusion_of :state,
  #   in: VALID_STATES
  
  validates_numericality_of :total_employees
 	validates_format_of :twitter_url, with: URI::regexp(%w(http https)), :allow_blank => true, :allow_nil => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
  validates_format_of :facebook_url, with: URI::regexp(%w(http https)), :allow_blank => true, :allow_nil => true
  
  validates :name, uniqueness: {scope: :user_id}, presence: true
 	belongs_to :user,
 	  inverse_of: :restaurants
	
  has_many :cuisines, through: :type_of_cuisines
  has_many :type_of_cuisines,
    dependent: :destroy
  
  has_many :neighborhoods, through: :areas
  has_many :areas,
    dependent: :destroy

  has_many :aware_employees,
   	inverse_of: :restaurant,
    dependent: :destroy 
  
  has_many :changeorders,
   	inverse_of: :restaurant,
    dependent: :destroy 


  accepts_nested_attributes_for :areas, :reject_if => lambda { |a| a[:neighborhood_id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :aware_employees, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :type_of_cuisines, :reject_if => lambda { |a| a[:cuisine_id].blank? }, :allow_destroy => true

  geocoded_by :restaurant_location
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }



  def restaurant_location 
    [address, city, state, zip].compact.join(', ')
  end

  searchable do
    text :name 
    text :address
    text :tags                        
    string :city                              
    string :state
    integer :zip                       
    text :description
    boolean :kid_friendly
    boolean :approved
    boolean :is_visible
    double :latitude
    double :longitude
    latlon(:location) { Sunspot::Util::Coordinates.new(latitude, longitude) }
    string :cuisines_name, :multiple => true do
      cuisines.map { |cuisine| cuisine.name}
    end
    string :hood_name, :multiple => true do
      neighborhoods.map { |neighborhood| neighborhood.name}
    end
    string :worker, :multiple => true do
      z = aware_employees.map  do |emp|
        emp.roles.map do |r|
          r.role
        end
      end
      z.flatten
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_user!, 
              :only => [:new, :edit, :create, :update, :delete]
  def index
   if (params[:city] || params[:state_search]).present? 
     @search  = Restaurant.solr_search do
      def whereat
      [params[:addy], params[:city], params[:state_search], params[:zip]].compact.join(', ')
      end
      def howfar 
        params[:within].to_i * 1.60934
      end
      with(:location).in_radius(*Geocoder.coordinates(whereat), howfar)
     end
     @restaurants = @search.results
   else
    @search  = Restaurant.solr_search do
      with(:location).in_radius(29.587359,-95.515556, 100)
     end
     @restaurants = @search.results
    end
  end

  def new
		  @states = []
    	@user = current_user
    	@restaurant = Restaurant.new
      @employee=@restaurant.aware_employees.build
      @employee.restaurant_roles.build
      @restaurant.areas.build
      @restaurant.type_of_cuisines.build
      @role = Role.all
      @type = ['ServSafe Allergens Online Course', 'AllerTrain']
    	State.all.each do |state|
    	 @states << state.abbreviation
    	end
  end
	def create
	 @user = current_user
   @restaurant = Restaurant.new(restaurant_params)
   @restaurant.user_id = current_user.id
   
    respond_to do |format|
      if @restaurant.save
        RestaurantMailer.create_email(@user, @restaurant).deliver
        AdminMailer.admin_create_email(@user, @restaurant).deliver
        save_url(@restaurant)
        save_nests(@restaurant)
        $old_form = ''
        format.html { redirect_to current_user, notice: 'Thank you for adding your restaurant to the SafeFARE database. The SafeFARE team will review the information you provided and will respond within two business days. If we need more information before approving your listing, you will receive a detailed email from our team.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
      $old_form = @restaurant
        format.html { redirect_to new_user_restaurant_path(current_user), notice: @restaurant.errors.full_messages }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
        
      end
    end
  end
  def save_url(restaurant)
    if Restaurant.where(name:restaurant.name).length > 1
              Restaurant.update(restaurant.id, url: restaurant.name.gsub(/[ ']/, '-') + Restaurant.where(name:restaurant.name).length.to_s)
          else
              Restaurant.update(restaurant.id, url: restaurant.name.gsub(/[ ']/, '-'))

          end
  end
  def destroy
     @restaurant =  Restaurant.find(params[:id])
    respond_to do |format|
      if @restaurant.delete

        format.html { redirect_to current_user, notice: "Successfully Deleted #{@restaurant.name}" }
      else
        format.html { redirect_to root_path, notice: 'There was an error on your form' }
      end
    end
    
  end
  def edit
    @notice = ''
    @cuisines = []
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.aware_employees.length == 0
      @notice = "Because you have not added any Aware Employees, your restaurant cannot be added to our searchable database.  Please add at least one."
    end
    @states = []  
    @type = ['ServSafe Allergens Online Course', 'AllerTrain']
    Cuisine.all.each do |x|
      if @restaurant.cuisines.include?(x) then puts x else @cuisines << x end 
    end
    State.all.each do |state|
      @states << state.abbreviation
    end
  end
  def update   
    @restaurant = Restaurant.find(params[:id])
  
    if @restaurant.update_attributes(restaurant_params)
  
      edit_nests 
      redirect_to edit_user_restaurant_path, notice: "Thanks for updating your restaurant, #{current_user.name}"
    else 
    redirect_to edit_user_restaurant_path, notice: @restaurant.errors.full_messages 
    end
  end
  
  def show

   if params[:url] == nil
    @restaurant = Restaurant.find(params[:id])
  else 
      @restaurant = Restaurant.find_by_url(params[:url])


  end
    @roles = []

    @employees = @restaurant.aware_employees.length
    @percent = ((@employees.to_f/@restaurant.total_employees.to_f) * 100).round(1)
    if @restaurant.repos != nil
    end
    @restaurant.aware_employees.each do |emp|
      emp.roles.each do |role|
        if @roles.include?(role.role)
          p 'exst'
        else
          @roles << role.role
        end
      end
    end
    respond_to do |format|
      format.html{  }
      format.json { render json: [@restaurant,@restaurant.cuisines,@roles,@employees] }
      end
  end
	private	
		def restaurant_params
      	params.require(:restaurant).permit(:name,:url,:address,:city,:state, :email, :phone,:repos,
          :hours,:approved,:kid_friendly,:website,:facebook_url,:twitter_url,:allergy_eats_url,:role_id,:image,
          :zip,:logo,:total_employees,:description,:is_visible,cuisine_ids:[],neighborhood_ids:[],
          aware_employees_attributes:[:name,:id, :verification,:expiration, :cert_type,role_ids:[],restaurant_roles_attributes:[role_id:[]]],
          type_of_cuisines_attributes:[:id,:restaurant_id,cuisine_id:[]],
          areas_attributes:[:id,:restaurant_id,neighborhood_id:[]]
        )
		end
  
    def edit_nests
      #edit cuisine nests
  
        params[:restaurant][:cuisine_ids].each do |cuisine|
          if cuisine == ''
            TypeOfCuisine.where(restaurant_id: @restaurant.id).each do |record|
              record.destroy
              @restaurant.update!(tags: ' ')
            end
          else
            TypeOfCuisine.create(restaurant_id: @restaurant.id, cuisine_id: cuisine )
             @restaurant.update!(tags: @restaurant.tags + ' ' + Cuisine.find(cuisine).name)
          end
        end
      # edit neighborhoods
        params[:restaurant][:neighborhood_ids].each do |hood|
          if hood == ''
            Area.where(restaurant_id: @restaurant.id).each do |record|
              record.destroy
            end
          else
            Area.create(restaurant_id: @restaurant.id, neighborhood_id: hood )
              @restaurant.update!(tags: @restaurant.tags + ' ' + Neighborhood.find(hood).name)
          end
        end
        #edit employee roles
        if params[:restaurant][:aware_employees_attributes] != nil
          params[:restaurant][:aware_employees_attributes].each do |employee|
            this_emp = AwareEmployee.where(name:employee[1][:name], restaurant_id: @restaurant.id).first
            next if this_emp == nil
            if employee[1][:role_ids] != nil
               employee[1][:role_ids].each do |role|  
                 if role == ''
                   RestaurantRole.where(aware_employee_id:this_emp.id).each do |record|
                     record.destroy
                   end
                 else
                  RestaurantRole.create(aware_employee_id:this_emp.id, role_id:role)
                  AwareEmployee.where(name:this_emp.name, restaurant_id: @restaurant.id).each do |x|
                    if x != this_emp then x.destroy end
                  end
                 end
               end
            else
              employee[1][:restaurant_roles_attributes].first[1][:role_id].each do |role|
                if role !='' then RestaurantRole.create(aware_employee_id:this_emp.id, role_id:role) end
              end
              AwareEmployee.where(name:this_emp.name, restaurant_id: @restaurant.id).each do |x|
                    if x != this_emp then x.destroy end
              end
            end
          end
        end 
    end
    def save_nests(this_restaurant)
      # Save Cuisine Nest
      params[:restaurant][:type_of_cuisines_attributes].first[1][:cuisine_id].each do |cuisine|
        if cuisine != '' 
          TypeOfCuisine.create(restaurant_id: this_restaurant.id, cuisine_id: cuisine )
          this_restaurant.update!(tags: this_restaurant.tags + ' ' + Cuisine.find(cuisine).name)
        end
      end
      # End Cuisine
      # Save Neighborhood Nest
        params[:restaurant][:areas_attributes].first[1][:neighborhood_id].each do |hood|
          if hood != '' 
           Area.create(restaurant_id: this_restaurant.id, neighborhood_id: hood )
            this_restaurant.update!(tags: this_restaurant.tags + ' ' + Neighborhood.find(hood).name)
         end
        end
      # End Neighborhood  
      # Save Employee Roles
      #   iterate through aware_employees
         params[:restaurant][:aware_employees_attributes].each do |employee|
          #find saved emplpyee with the correct name AT the current restaurant
           saved_employee = AwareEmployee.where(name: employee[1][:name], restaurant_id: this_restaurant.id).first
        #   #iterate through restaurant roles and save
           if saved_employee != nil 
             employee[1][:restaurant_roles_attributes].first[1][:role_id].each do |role|
               if role != '' then RestaurantRole.create(aware_employee_id: saved_employee.id, role_id: role ) end
              end 
            end  
          end
      end  
    end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_aware_employee_fields.html.erb
<div class="aware-cont">
	<div class="col-xs-12 form-row">
		<p class='form-label validate emp_name'>Name</p>
		<%= f.input :name, label: false, input_html: { class: "req" }   %>
		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row">
		<p class='form-label validate Verifcation'>Training Certificate Number</p>
		<%= f.input :verification, label: false, input_html: { class: "req" }  %>
		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row">
		<p class='form-label'>Certification Type</p>
			<%= f.input :cert_type, collection: @type, required: true, label: false, include_blank: false,input_html: { class: "" } %>
		<span class='feedback'></span>
	</div>			
	<div class="col-xs-12 form-row">
		<p class='form-label'>Expiration</p>
		<%= f.input :expiration, label: false, as: :date, :start_year=> Date.today.year, :end_year =>Date.today.year + 20, :order =>[:month, :day, :year] %>

		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row emp_role">
		<p class='form-label'>Role</p>
		<%= f.simple_fields_for :restaurant_roles do |builder| %>
			<%= render "restaurant_role_fields" , :f => builder %>
		<% end %>
		<div class="role-click">
			<%= link_to_add_fields "Add Role", f, :restaurant_roles %>
		</div>
	</div>
	<hr>
</div>

app/views/restaurants/_edit_aware_employee_fields.html.erb
<div class="aware-cont">
	<div class="col-xs-12 form-row">
		<p class='form-label validate emp_name'>Name</p>
		<%= f.input :name, label: false, input_html: { class: "req" }   %>
		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row">
		<p class='form-label validate Verifcation'>Training Certificate Number</p>
		<%= f.input :verification, label: false, input_html: { class: "req" }  %>
		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row">
		<p class='form-label'>Certification Type</p>
			<%= f.input :cert_type, collection: @type, required: true, label: false, input_html: { class: "" } %>
		<span class='feedback'></span>
	</div>			
	<div class="col-xs-12 form-row">
		<p class='form-label'>Expiration</p>
		<%= f.input :expiration, label: false, as: :date, :start_year=> Date.today.year, :end_year =>Date.today.year + 20, :order =>[:month, :day, :year] %>
		<span class='feedback'></span>
	</div>
	<div class="col-xs-12 form-row emp_role edit">
		<p class='form-label'>Role</p>
		<%= f.association :roles, label:false, multiple: true, collection: Role.all, label_method: :role, value: :id, input_html: { class: "chosen-select req", multiple: true, style: 'width:255px; height:200px;'}  %>
 	</div>
</div>

app/views/restaurants/_edit_restaurant_form.html.erb
<%= simple_form_for [ current_user,@restaurant ], html: {novalidate: true} do |f| %>

	<div class="col-sm-12 col-xs-12">
		<div class="col-xs-12 form-row validate name">
			<p class='form-label' style=''>Restaurant Name<span class='required_field'>*</span></p>
			<%= f.input :name, label: false, input_html: { class: "req" }   %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Visible</p>
			<%= f.input :is_visible, label: false, input_html: { class: "req" },  as: :radio_buttons    %>
			<div class='feedback'><div></div></div>
			 <p class="disclaim">Choose <span class='required_field'>No</span> only if you do not want <span class='required_field'><%= @restaurant.name %></span> to show up in search results.</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Kid Friendly</p>
			<%= f.input :kid_friendly, label: false, input_html: { class: "req margin-top" }, as: :radio_buttons    %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row validate address">
			<p class='form-label'>Address<span class='required_field'>*</span></p>
			<%= f.input :address, label: false, input_html: { class: "req" } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row validate city">
			<p class='form-label'>City<span class='required_field'>*</span></p>
			<%= f.input :city, label: false, input_html: { class: "req" } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row state">
			<p class='form-label'>State<span class='required_field'>*</span></p>
			<%= f.input :state, collection: @states, include_blank: 'Select...',required: true, label: false, input_html: { class: "req" } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row validate zip">
			<p class='form-label'>ZIP<span class='required_field'>*</span></p>
			<%= f.input :zip, label: false, as: :string, input_html: { class: "req" } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row">
			<div class="no-label-wrap">
				<span id='check'>Check Address</span>. You may move the pin to a desired location.
			</div>
		</div>
		<div class="col-xs-12 form-row">
			<div class="no-label-wrap">
				<div class="map-wrap">	
					<div id="map-canvas" ></div>
					<%= f.input :repos, label: false, as: :hidden %>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12 form-row validate number_of_employees">
			<p class='form-label'>Total Number of Employees<span class='required_field'>*</span></p>
			<%= f.input :total_employees, label: false, input_html: { class: "req", min: '0' } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Hours</p>
			<%= f.input :hours, label: false, input_html: { placeholder:'8AM-7PM M-F', class: "req", min: '0' } %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Neighborhood</p>
			<%= f.association :neighborhoods, label:false, multiple: true, collection: Neighborhood.all, label_method: :name, value: :id, input_html: { class: "chosen-select req", multiple: true }  %>
			<div class='feedback'><div></div></div>
			<p class="disclaim">Please begin by entering in a neighborhood. Your neighborhood will be autofill. You can choose multiple. If you don't see your neighborhood, feel free to contact us.</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Food Allergy Policies</p>
			<%= f.input :description, label: false %>
			<div class='feedback'><div></div></div>
			 <p class="disclaim">Please describe your policies (e.g., Please advise the hostess of your allergies and ask for Executive Chef Matt Smith).</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Cuisine</p>
			<%= f.association :cuisines, multiple: true, label:false, collection: Cuisine.all, label_method: :name, value: :id, input_html: { class: "chosen-select req", multiple: true }  %>
			<span class='feedback'></span>
			<p class="disclaim">Please begin by entering in a cuisine type. Your cuisine will be autofill. You can choose multiple cuisines.</p>
		</div>
		<% if @restaurant.logo.url != nil%>
			<div class="white-space"></div>
			<div class="col-xs-12 form-row">
				<p class='form-label'>Current Logo</p>
			<img src='<%=@restaurant.logo.url %>'>
			</div>
		<% end %>
		<% if @restaurant.image.url != nil %>
			<div class="col-xs-12 form-row">
				<p class='form-label'>Current Image</p>
				<img src='<%=@restaurant.image.url %>'>
			</div>
		<% end %>
		<div class="white-space"></div>
		<h2><% if @restaurant.logo.url != nil%>Change<%end%> Logo/Image</h2>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Logo</p>
			<%= f.file_field :logo, label: false, input_html: { class: "req" }   %>
			<p class="disclaim">We recommend using a photo around 200 x 200 </p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Image</p>
			<%= f.file_field :image, label: false, input_html: { class: "req" }   %>
			<p class="disclaim">We recommend using a photo around 300 x 300 </p>
		</div>

		<div class="white-space"></div>

		<h2>Contact/Social Network Information</h2>
		<div class="col-xs-12 form-row validate email">
			<p class='form-label'>Email<span class='required_field'>*</span></p>
			<%= f.input :email, label: false, input_html: { class: "req" }  %>
			<div class='feedback'><div></div></div>
		</div>		
		<div class="col-xs-12 form-row">
			<p class='form-label'>Phone</p>
			<%= f.input :phone,as: :tel, label: false, input_html: {placeholder: "(888)-888-8888"} %>
			<div class='feedback'><div></div></div>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Website</p>
			<%= f.input :website, label: false, input_html: {placeholder: "http://www.YourGreatRestaurant.com"} %>
			<div class='feedback'><div></div></div>
			<p class="disclaim">Please include http://www.</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Facebook</p>
			<%= f.input :facebook_url, label: false, input_html: {placeholder: "http://www.facebook.com/YourGreatRestaurant"} %>
			<div class='feedback'><div></div></div>
			<p class="disclaim">Please include http://www.</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Twitter</p>
			<%= f.input :twitter_url, label: false, input_html: {placeholder: "http://www.twitter.com/YourGreatRestaurant"} %>
			<div class='feedback'><div></div></div>
			<p class="disclaim">Please include http://www.</p>
		</div>
		<div class="col-xs-12 form-row">
			<p class='form-label'>Allergy Eats</p>
			<%= f.input :allergy_eats_url, label: false %>
			<div class='feedback'><div></div></div>
			<p class='disclaim'>If your restaurant is listed on www.AllergyEats.com, please add the AllergyEats URL here.</p>
		</div>

		<div class="white-space"></div>

	
		<h2>Add Allergy Aware Employees</h2>
		<div class="col-xs-12 form-row">
			<div class="blue-form">
				<div class="col-xs-12">
					<%= f.simple_fields_for :aware_employees do |builder| %>
						<%= render "edit_aware_employee_fields", :f => builder %>
					<div class="col-xs-12 form-row">
						<div class="no-label-wrap">
							<%= link_to "Remove Employee", user_restaurant_aware_employee_path(current_user, @restaurant, builder.object.id), :method => :delete, :class => 'nav-link orange' %>
						</div>
					</div>
					<hr>
					<% end %>
					<%= link_to_add_fields "Add An Employee", f, :aware_employees %>
					<div class='remove_fields'>Remove An Employee</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 form-row">
		
				<%= f.button :submit, :class => "nav-link left" %>
				<div class="nav-link orange signup">
					<%= link_to "Delete Restaurant", user_restaurant_path(current_user, @restaurant), :method => :delete, :class => 'action' %>
				</div>
			
		</div>
	</div>
	
<% end %>
<% if @restaurant.repos == '' %>
	<script>
		initialize();
		
			var address = $('#restaurant_address')[0];
			var city = $('#restaurant_city')[0];
			var state = $('#restaurant_state')[0];
			var params = $(address).val() + ',' + $(city).val() + ',' + $(state).val() ;
			var params = params.replace(/\s+/g, '+')
				if (params.length < 5) {
					alert('please provide a valid address');
				}else{
					geocode(params);
				}
		
	</script>
<%else%>
	<script>
			initialize();
			parseLoc(<%= @restaurant.repos %>);		
			$('#map-canvas').animate({opacity:1},500);
	</script>
<%end%>

<script>
if (isIE) {$('.ie-gonem, .role-click a').fadeOut();}
$( "#check" ).click(function() {
	  event.preventDefault();
	  var address = $('#restaurant_address')[0];
	  var city = $('#restaurant_city')[0];
	  var state = $('#restaurant_state')[0];
	  var params = $(address).val() + ',' + $(city).val() + ',' + $(state).val() ;
  	  params = params.replace(/\s+/g, '+')
	  if (params.length < 5) {
	  	alert('please provide a valid address');
	  }else{

	  	geocode(params);
		
		}
	  });
$('.chosen-select').chosen({placeholder_text_multiple: '-------------------'});
$('input, textarea, .select').on('blur',function(){ 
	var id = $(this).attr('id');
	if ( validate_element(this) == true ){
		$("#" + id).css('border', '1px solid green');
	}else{
		$("#" + id).css('border', '1px solid red');
	}
});

$('.add_fields').on('click', function(){
	setTimeout(function(){
		$('.role-click a').trigger('click');
	}, 10)
		$('.role-click a').css('display', 'none');
		$('.role-click a').remove();
})
	$('.sub').on('click', function(){
		$('.submit').trigger('click');
	})

</script>

app/views/restaurants/_restaurant_role_fields.html.erb
<%= f.input :role_id, collection: Role.all, multiple: true, value: :id, label_method: :role, label: false, input_html: { class: "chosen-select req", multiple: true, style: 'width:255px; height:200px;'} %>

app/views/restaurants/edit.html.erb
<style>
.active{
	display:block;
}
</style>
<div class="edit-restaurant-section">

	
		<div class="alert notice"><% if @notice != '' %><span class='required_field'> <%=@notice%></span><br><%end%><%= notice %><%= alert %></div>
	
	<div class="section-wrapper">
		<% if current_user.id != @restaurant.user_id %>
			<p> This restaurant does not belong to you </p>
		<% else %>
			<% if @restaurant.approved != true %>
				<h5 style='margin-top:20px;'> This Restaurant has <span style='color:red'> Not Yet </span> Been Approved by The SafeFARE Staff </h5>
			<% end %> 
			<h2 class="orange-header padding-left" style='margin-top:15px'><%=@restaurant.name%></h2>
			<%= render 'edit_restaurant_form' %>
		<%end%>
		<div style='clear:both'></div>	
	</div>
</div>
<script>
var start_length = $('.aware-cont').length;
$('.remove_fields').click(function(event){
 	if ($('.aware-cont').length > start_length){
		$('.aware-cont').last().remove()
	}
})
</script>

app/views/restaurants/index.html.erb
  <div class="col-sm-12" style='text-align:center;'>
      <div class="center error">
        <h1>You've ended up in the wrong place</h1>
        <%= link_to "Get Me Out Of Here!", '/for-restaurants', class:'nav-link' %>
      </div>  
  </div>
   